import type { Form } from '@/store/slices/formsSlice'
import { FORM_TYPES, QUESTION_TYPES } from './constants'

export const DUMMY_FORMS: Form[] = [
  {
    id: 'form-1',
    title: 'Product Launch Registration',
    description: 'Collect registrations for the upcoming product launch event',
    type: FORM_TYPES.REGISTRATION,
    responses: 247,
    completionRate: 84,
    isPublished: true,
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-12T15:30:00Z',
    questions: [
      {
        id: 'q-1-1',
        type: QUESTION_TYPES.WELCOME_SCREEN,
        title: 'Welcome to our Product Launch!',
        description: 'We are excited to have you join us. Register below to secure your spot.',
        required: false,
        order: 0,
      },
      {
        id: 'q-1-2',
        type: QUESTION_TYPES.SHORT_TEXT,
        title: 'What is your full name?',
        required: true,
        order: 1,
      },
      {
        id: 'q-1-3',
        type: QUESTION_TYPES.EMAIL,
        title: 'What is your email address?',
        required: true,
        order: 2,
      },
      {
        id: 'q-1-4',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        title: 'How did you hear about us?',
        required: false,
        options: ['Social Media', 'Friend Referral', 'Search Engine', 'Newsletter', 'Other'],
        order: 3,
      },
      {
        id: 'q-1-5',
        type: QUESTION_TYPES.THANK_YOU_SCREEN,
        title: 'Thank you for registering!',
        description: 'We will send you a confirmation email shortly.',
        required: false,
        order: 4,
      },
    ],
  },
  {
    id: 'form-2',
    title: 'Customer Feedback Survey',
    description: 'Gather insights from customers about their experience',
    type: FORM_TYPES.SURVEY,
    responses: 89,
    completionRate: 72,
    isPublished: true,
    createdAt: '2026-02-05T08:00:00Z',
    updatedAt: '2026-02-11T12:00:00Z',
    questions: [
      {
        id: 'q-2-1',
        type: QUESTION_TYPES.RATING,
        title: 'How would you rate your overall experience?',
        required: true,
        order: 0,
      },
      {
        id: 'q-2-2',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        title: 'Which features do you use the most?',
        required: false,
        options: ['Form Builder', 'Analytics', 'Integrations', 'Templates', 'AI Assistant'],
        order: 1,
      },
      {
        id: 'q-2-3',
        type: QUESTION_TYPES.LONG_TEXT,
        title: 'What improvements would you suggest?',
        required: false,
        order: 2,
      },
    ],
  },
  {
    id: 'form-3',
    title: 'Sales Discovery Call Booking',
    description: 'Book a call with our sales team to discuss your needs',
    type: FORM_TYPES.CALL_BOOKING,
    responses: 34,
    completionRate: 91,
    isPublished: true,
    createdAt: '2026-01-28T14:00:00Z',
    updatedAt: '2026-02-09T09:00:00Z',
    questions: [
      {
        id: 'q-3-1',
        type: QUESTION_TYPES.SHORT_TEXT,
        title: 'What is your company name?',
        required: true,
        order: 0,
      },
      {
        id: 'q-3-2',
        type: QUESTION_TYPES.EMAIL,
        title: 'Your work email',
        required: true,
        order: 1,
      },
      {
        id: 'q-3-3',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        title: 'What is your team size?',
        required: true,
        options: ['1-5', '6-20', '21-50', '51-200', '200+'],
        order: 2,
      },
      {
        id: 'q-3-4',
        type: QUESTION_TYPES.DATE,
        title: 'Preferred call date',
        required: true,
        order: 3,
      },
    ],
  },
  {
    id: 'form-4',
    title: 'SaaS Pricing Qualification',
    description: 'Qualify leads for the right pricing tier',
    type: FORM_TYPES.SALES,
    responses: 156,
    completionRate: 67,
    isPublished: false,
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-02-08T16:45:00Z',
    questions: [
      {
        id: 'q-4-1',
        type: QUESTION_TYPES.SINGLE_CHOICE,
        title: 'What is your monthly budget for tools?',
        required: true,
        options: ['Under $50', '$50-$200', '$200-$500', '$500+'],
        order: 0,
      },
      {
        id: 'q-4-2',
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
        title: 'Which features are most important to you?',
        required: true,
        options: ['AI Form Generation', 'Custom Branding', 'Advanced Analytics', 'API Access', 'Team Collaboration'],
        order: 1,
      },
    ],
  },
]
